### ISSUE TITLE
Does not work witt jQuery 1.9.1 + IE7

### ISSUE THREAD

**Issue by hubiktomas** [rapidexp/jquery-h5form#10]
The browser throws the following error and does not activate h5form:

Error: '$.browser.version' is null or not an object

Tested with jQuery 1.9.1 and Internet Explorer 7

**Comment by rapidexp** [comment]
Many API has been removed in jQuery 1.9.
If you want to target older browser versions, you should use jQuery 1.8 or earlier.

http://jquery.com/upgrade-guide/1.9/

I will not longer support jQuery 2.0, but I'm wondering about 1.9.

Oops, IE 7 with jQuery 1.8 also has an another error....

**Comment by rapidexp** [comment]
I updated laster version.
- Support jQuery 1.9 (exclude 1.6 or earlier)
- Fixed error in IE 7 with the number or date states.

**Comment by hubiktomas** [comment]
Works fine now. Thanks.
