### ISSUE TITLE
Support for checkValidity()

### ISSUE THREAD

**Issue by syvalta** [rapidexp/jquery-h5form#11]
Often you would like to validate a form for example before an ajax submit. HTML5 provides checkValidity() for this. It would be great if h5form could provide support for this.

https://developer.mozilla.org/en-US/docs/DOM/HTMLFormElement#Methods
http://msdn.microsoft.com/en-us/library/ie/hh772948%28v=vs.85%29.aspx

Btw, is there any possibility to trigger validation programmatically in the current version?

**Comment by rapidexp** [comment]
I thought about it only a little, too.
A good idea will appear sometime.

**Comment by rapidexp** [comment]
By the way, the error information is stored in data of the element.
It has already entered before the submitt of the user.

https://github.com/rapidexp/jquery-h5form/blob/master/jquery.h5form--laster/en/jquery.h5form--laster.js#L183

You may be get it using $.hasData(element).

**Comment by rapidexp** [comment]
I intend to insert the following functions in Line 201.
Is this enough to be able to help ajax?

```
        $.fn.checkValidity = function(message) {
            var ui = $(this);
            if (hasCustomValidity) {
                return ui.get(0).checkValidity();
            } else {
                return (!ui.data('customValidity'));
            }
        };
```

**Comment by rapidexp** [comment]
I updated the laster version.
The folowing methods is available now.

```
$.fn.h5form.checkValidity(element);
$.fn.h5form.setCustomValidity(element, message);
```
