### ISSUE TITLE
Firefox/IE9 Number input buttons create Times

### ISSUE THREAD

**Issue by traeblain** [rapidexp/jquery-h5form#12]
This happens on something I'm working on and your demo.  But in Firefox (latest stable) and IE9 (all I've tested), an input of type="number" gives you the up and down arrows next to the box...as it should...but if you use them it creates a Time value.  ie. "00:00:01".

**Comment by rapidexp** [comment]
Yes, It has been already settled in the last version.

https://github.com/rapidexp/jquery-h5form/blob/master/jquery.h5form--laster/README.html#L1007
