### ISSUE TITLE
Maxlength on a textarea does not allow typing in IE8

### ISSUE THREAD

**Issue by armyofgnomes** [rapidexp/jquery-h5form#14]
When trying to type in a textarea field with a maxlength, it does not allow any typing at all.

Changing the code to this allows it to work:

``` javascript
// Maxlength
if (reqMaxlength && ui.is('textarea') &&
  (getAttr(ui, 'maxlength'))) {
  // Keypress event attach
  var evKeypress = (function(ev) {
    var cc = ev.charCode || ev.keyCode;
    if (($.inArray(cc, [8, 9, 37, 39, 46]) < 0) &&
      (this.value.length >= getAttr(ui, 'maxlength'))) {
      return false;
    }
    return true;
  });
  ui.unbind('keypress', evKeypress).keypress(evKeypress);
}
```

Also, I'm not sure if it is a separate issue or not, but maxlength does not apply to textarea elements added to the page by Javascript after the page has loaded.

**Comment by rapidexp** [comment]
Thank you. I will check your code later.

This plugin does not apply to any controls that do not exist at the time of loading.
Please set "h5form-dynamic" to the class name of the text area. Or, use the dynamicHtml option for the text area.
Then, it will be verified at the time of submission.

**Comment by rapidexp** [comment]
Hmm, I seem a utility is needed to initialize the validation.

**Comment by rapidexp** [comment]
I have understand your code.
You changed the value of the maxlength dynamically, didn't you?

**Comment by armyofgnomes** [comment]
Ahh, I see. It does verify the maxlength at submission if I add h5form-dynamic to the textarea, but it does not limit the typing like it does with the elements that were already on the page.
