### ISSUE TITLE
Error on ie8 using jquery 1.8.2

### ISSUE THREAD

**Issue by scottillogical** [rapidexp/jquery-h5form#2]
Webpage error details

User Agent: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1; Trident/4.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0; .NET4.0C)
Timestamp: Thu, 8 Nov 2012 21:03:51 UTC

Message: Syntax error
Line: 75
Char: 7
Code: 0
URI: http://10.160.100.43:4011/assets/jquery.h5form-2.7.1.js?body=1

Which is I think on line

 eval(opts.hasOptions[i] + '=true;');

**Comment by rapidexp** [comment]
Thank you for your report.

However, the error did not come out to the extent that I have checked on IE8 using jquery 1.8.2.

As a test, I tried to edit as follows: testing page.
As expected, the placeholder attribute no longer works on IE8.

$(function() {
&nbsp;  $('form').h5form({
&nbsp; &nbsp;    hasOptions: [ 'hasPlaceholder' ]
&nbsp;  });
});

What are the options that you have specified?
