### ISSUE TITLE
Incorrect array iteration

### ISSUE THREAD

**Issue by ondras** [rapidexp/jquery-h5form#6]
Arrays should NOT be iterated via "for (p in array)", as in https://github.com/rapidexp/jquery-h5form/blob/master/jquery.h5form-2.8.1/en/jquery.h5form-2.8.1.js#L75. This approach breaks compatibility with Array prototype enhancements (such as JS 1.6 polyfills for older IEs).

**Comment by rapidexp** [comment]
Oops, I was a veritable php programmer.
I will check all the code.

**Comment by rapidexp** [comment]
I Corrected the syntax of the array in the laster.
