### ISSUE TITLE
Form checking after first submit

### ISSUE THREAD

**Issue by hubiktomas** [rapidexp/jquery-h5form#7]
Hello,

I think, that there should be a feature to turn form validation after first pressing of submit button. Otherwise there are these red inputs even though the user does not want to use the form.

T.

**Comment by rapidexp** [comment]
Thank you for your suggestion.

Well, I will consider.

**Comment by rapidexp** [comment]
Hmm, it is necessary to validation at load time for this plugin.

This means that, all the elements are set in the error state for the first time.
When you edit these elements, the error state is cleared each time..
Then when you submit, it is only to show the errors that are already set.

As an alternative proposal, I tried not to change the background color in the first validation.

Please check the code in the laster.

**Comment by hubiktomas** [comment]
Thank you for the change. I do not know, if it is better now. Now the behavior is a little bit weird. Would it be possible to set some flag signalizing submit pushed and the css color will apply ony when the button was pushed? And then refresh the state (color) of all inputs color after each submit? Now there are situations where there is a popup with error message, but no color. And also celar all popups after change of any field because otherwise there could be more popups at a time and they could overlay.

**Comment by rapidexp** [comment]
I understand what you mean, but I can not change the program structure.
I tried not to stop until the end of the scan when submitting.

What about now?

**Comment by hubiktomas** [comment]
Super. Now It works as I expected. The form looks normal on load and shows color on all bad inputs on submit. Thank you very much!

**Comment by rapidexp** [comment]
You're welcome.
