### ISSUE TITLE
Bad popup position

### ISSUE THREAD

**Issue by hubiktomas** [rapidexp/jquery-h5form#8]
I do not know, if this is bug in the h5form or in my CSS. At least it is not documented. The position of the popups are bad in on my pages.

http://www.ibento.cz/kontakty.php

When you fill something in the first field, email in the second and nothing in the third, the popup bubble is somewhere outside the form. Could you. please, let me know, if it is the problem in my CSS or if it is some wrong handling of the popup positions?

Thanks.

**Comment by rapidexp** [comment]
The message is simply inserted just before the elements as follows.
I think the float of LI is causing.

![Capture Image](http://www.rapidexp.com/images/temp/h5form-response.png)

**Comment by hubiktomas** [comment]
Ok, thanks. I will take a look at it. Could you, please, add this to some documentation/wiki. How to write the form in order to be compatible with h5form. Thanks.

**Comment by rapidexp** [comment]
Well, I think I will summarize to document.
