### ISSUE TITLE
Verifying checkbox

### ISSUE THREAD

**Issue by hubiktomas** [rapidexp/jquery-h5form#9]
<input type="checkbox" required

does not work

**Comment by rapidexp** [comment]
Hmm, I did not have the need in the check box.
Well, it is a checkbox to apply...

**Comment by hubiktomas** [comment]
It is useful for example when you have to check some kind of "I agree with terms of the service" and so on.

**Comment by rapidexp** [comment]
I commited to laster.

**Comment by hubiktomas** [comment]
Thanks. Works fine.
